"""
MongoDB collections for the adaptive quiz system.
These are reference schemas — Motor creates collections automatically.

Collections:
  quiz_sessions    — one per quiz attempt (settings, status, final report)
  quiz_questions   — every question generated in a session
  quiz_attempts    — every answer submitted by the student
  weak_topics      — aggregated weak concept tracking per user
  study_history    — timeline of all quiz activity per user
"""

QUIZ_SESSION_SCHEMA = {
    "_id": "str (uuid)",
    "user_id": "str",
    "document_ids": ["str"],
    "difficulty": "easy | medium | hard | mixed",
    "question_types": ["mcq", "true_false", "fill_blank", "short_answer", "long_answer"],
    "total_questions_requested": "int",
    "status": "active | completed | abandoned",
    "current_phase": "initial | adaptive | practice | final",
    "score": "float (0-100)",
    "avg_confidence": "float",
    "time_started": "datetime",
    "time_completed": "datetime | None",
    "report": "dict | None",
    "created_at": "datetime",
}

QUIZ_QUESTION_SCHEMA = {
    "_id": "str (uuid)",
    "session_id": "str",
    "user_id": "str",
    "question_text": "str",
    "question_type": "mcq | true_false | fill_blank | short_answer | long_answer",
    "difficulty": "easy | medium | hard",
    "topic": "str",
    "concept": "str",
    "options": ["str"],           # MCQ/T-F only
    "correct_answer": "str",
    "explanation": "str",
    "page_reference": "int | None",
    "source_document": "str",
    "is_adaptive": "bool",        # True if generated by adaptive engine
    "order": "int",
    "created_at": "datetime",
}

QUIZ_ATTEMPT_SCHEMA = {
    "_id": "str (uuid)",
    "session_id": "str",
    "question_id": "str",
    "user_id": "str",
    "user_answer": "str",
    "is_correct": "bool",
    "confidence": "float (0-1)",   # derived from time taken + correctness
    "time_taken_seconds": "int",
    "difficulty": "str",
    "topic": "str",
    "concept": "str",
    "feedback": {
        "correct_answer": "str",
        "explanation": "str",
        "why_wrong": "str | None",
        "real_world_example": "str",
        "memory_trick": "str",
        "related_concepts": ["str"],
        "page_reference": "int | None",
    },
    "created_at": "datetime",
}

WEAK_TOPIC_SCHEMA = {
    "_id": "str (uuid)",
    "user_id": "str",
    "topic": "str",
    "concept": "str",
    "wrong_count": "int",
    "total_attempts": "int",
    "accuracy": "float",
    "last_seen": "datetime",
    "mastered": "bool",
}

STUDY_HISTORY_SCHEMA = {
    "_id": "str (uuid)",
    "user_id": "str",
    "session_id": "str",
    "event": "quiz_started | quiz_completed | adaptive_triggered | concept_mastered",
    "metadata": "dict",
    "created_at": "datetime",
}